administration_mode: false
allow_on_admin_pages: false
#default_challenge: image_captcha/Image
add_captcha_description: false
description: ''
default_validation: 0
persistence: null
enable_stats: false
log_wrong_responses: false
