settings:
  default_form_file_limit: '22 MB'
html_editor:
  tidy: true
  disabled: true
file:
  make_unused_managed_files_temporary: true
  delete_temporary_managed_files: true
  file_public: true
  file_private_redirect: true
  file_private_redirect_message: 'Please login to access the uploaded file.'
  default_managed_file_extensions: 'gif jpg jpeg png bmp eps tif pict psd txt rtf html odf pdf doc docx ppt pptx xls xlsx xml avi mov mp3 mp4 ogg wav bz2 dmg gz jar rar sit svg tar zip'
  default_audio_file_extensions: 'mp3 ogg wav'
  default_document_file_extensions: 'txt rtf pdf doc docx odt ppt pptx odp xls xlsx ods'
  default_image_file_extensions: 'gif jpg jpeg png'
  default_video_file_extensions: 'avi mov mp4 ogg wav webm'
